name: Weather Pipeline CI/CD

on:
  push: 
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  test_and_fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo #makes a copy of application in virtual machine so it can run the other steps
        uses: actions/checkout@v4 #checks version of action is v4

      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-versions: "22"
      
      - name:
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      
      - name: Install dependencies
        run: npm ci

      - name: Fetch latest weather
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          WEATHER_CITY: ${{ secrets.CITY}}
        run: node fetchWeather.js
      
      - name: Commit weather data if changed
        run: |
            git config user.name "github-actions[bot]"
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add data/weather.json data/weather_log.csv || true
            git commit -m "ci: update weather data" || echo "No changes to commits"
            git push || echo "Push failed or no changes"

      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
